import type { Metadata } from "next";
import { Inter, Roboto_Mono, Kablammo, Caveat } from 'next/font/google'
import "./globals.css";
import Image from "next/image";

const kablammo = Kablammo({
    subsets: ['latin'],
    variable: '--font-kablammo',
    display: 'swap',
})

const caveat = Caveat({
    subsets: ['latin'],
    variable: '--font-caveat',
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${kablammo.variable} ${caveat.variable} antialiased  relative`}
            >
                <div className="fixed -z-40 top-0 left-0 h-screen w-full">
                    <Image
                        className="w-full h-full object-cover"
                        src={"/images/bg.png"}
                        width={1000}
                        height={1000}
                        alt="bg"
                    />
                </div>
                {children}
                
            </body>
        </html>
    );
}
