import type { Metadata } from "next";
import { Kablammo, Caveat } from 'next/font/google'
import "./globals.css";

const kablammo = Kablammo({
    subsets: ['latin'],
    variable: '--font-kablammo',
    display: 'swap',
})

const caveat = Caveat({
    subsets: ['latin'],
    variable: '--font-caveat',
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body
                className={`${kablammo.variable} ${caveat.variable} antialiased`}
                style={{ background: "#fff" }}
            >
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
